//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquidacionBonificaciones {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiquidacionBonificaciones.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se borro correctamente.
        /// </summary>
        internal static string BorrarUsuario {
            get {
                return ResourceManager.GetString("BorrarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted mismo se no se puede eliminar.
        /// </summary>
        internal static string EliminarMismoUsuario {
            get {
                return ResourceManager.GetString("EliminarMismoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error al guardar el historico de la liquidación.
        /// </summary>
        internal static string ErrorHistorico {
            get {
                return ResourceManager.GetString("ErrorHistorico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error al actualizar el Parametro: .
        /// </summary>
        internal static string ErrorId {
            get {
                return ResourceManager.GetString("ErrorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error, porfavor comuniquese con el administrador.
        /// </summary>
        internal static string ErrorProceso {
            get {
                return ResourceManager.GetString("ErrorProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso realizado con exito!!.
        /// </summary>
        internal static string Exitoso {
            get {
                return ResourceManager.GetString("Exitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta liquidación ya fue cerrada, cree un nuevo mes para poder continuar .
        /// </summary>
        internal static string LiquidacionCerrada {
            get {
                return ResourceManager.GetString("LiquidacionCerrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parametro a continuación no puede tener el mismo valor que antes: .
        /// </summary>
        internal static string ParametroIgual {
            get {
                return ResourceManager.GetString("ParametroIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen parametros, por favor validar.
        /// </summary>
        internal static string ParametrosNo {
            get {
                return ResourceManager.GetString("ParametrosNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error en el proceso, por favor comuniquese con el administrador del sistema.
        /// </summary>
        internal static string ProcesoError {
            get {
                return ResourceManager.GetString("ProcesoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se actualizo correctamente.
        /// </summary>
        internal static string UsuarioActualizado {
            get {
                return ResourceManager.GetString("UsuarioActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no valido.
        /// </summary>
        internal static string UsuarioNo {
            get {
                return ResourceManager.GetString("UsuarioNo", resourceCulture);
            }
        }
    }
}
