USE [Bonificacion_desarrollo]
GO

/****** Object:  Table [dbo].[BON_Perfil]    Script Date: 17/02/2020 3:17:54 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BON_Perfil](
	[ID] [int] NOT NULL,
	[PERFIL] [varchar](100) NULL,
 CONSTRAINT [PK_SCO_Perfil] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


