USE [Bonificacion_desarrollo]
GO

/****** Object:  Table [dbo].[BON_TipoVenta]    Script Date: 17/02/2020 3:18:49 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BON_TipoVenta](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NombreVenta] [varchar](20) NULL,
 CONSTRAINT [PK_Bon_TipoVenta] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


